x = input("Enter value of x :")
y = input("Enter value of y :")
print("value of x is ",x)
print("value of x is ",y)
print(x+y)
print(type(x))

a = int(input("Enter value of a :"))
b = int(input("Enter value of b :"))
print(a+b)
print(type(a))
